$NGL_shaderTextHash['Instancing.vert'] = ["//attribute vec3 position;",
"//  attribute vec3 normal;",
"//  attribute vec3 color;",
"attribute vec4 matrix1;",
"attribute vec4 matrix2;",
"attribute vec4 matrix3;",
"attribute vec4 matrix4;",
"",
"//  uniform mat4 projectionMatrix;",
"//  uniform mat4 modelViewMatrix;",
"",
"  varying vec3 vNormal;",
"  varying vec3 vColor;",
"",
"  mat4 computeMat(vec4 v1, vec4 v2, vec4 v3, vec4 v4) {",
"    return mat4(",
"      v1.x, v1.y, v1.z, v1.w,",
"      v2.x, v2.y, v2.z, v2.w,",
"      v3.x, v3.y, v3.z, v3.w,",
"      v4.x, v4.y, v4.z, v4.w",
"    );",
"  }",
"",
"  void main(void) {",
"    vColor = color;",
"    mat4 matrix = computeMat(matrix1, matrix2, matrix3, matrix4);",
"    vec4 updatePosition = matrix * vec4(position, 1.0);",
"    gl_Position = projectionMatrix * modelViewMatrix * updatePosition;",
"  }"
].join("\n");
